- name: Add .NET Core repo
  template:
    src: microsoft-prod.repo.j2
    dest: /etc/yum.repos.d/microsoft-prod.repo

- name: Install .NET Core runtime
  yum:
    name: "dotnet-runtime-{{ dotnet_version }}"
    state: latest

- name: Obtain DepotDownloader
  get_url:
    url: "https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_{{ depotdownloader_version }}/depotdownloader-{{ depotdownloader_version }}.zip"
    dest: "{{ steam_home }}/depotdownloader.zip"
    owner: steam
    group: steam
    mode: '0644'
  register: dd_dl

- name: Remove old DepotDownloader
  file:
    path: "{{ steam_home }}/depotdownloader"
    state: absent
  when: dd_dl.changed

- name: Create DepotDownloader directory
  file:
    path: "{{ steam_home }}/depotdownloader"
    state: directory
    owner: steam
    group: steam
    mode: '0755'

- name: Extract DepotDownloader
  become: yes
  become_user: steam
  unarchive:
    src: "{{ steam_home }}/depotdownloader.zip"
    dest: "{{ steam_home }}/depotdownloader"
    remote_src: yes
  when: dd_dl.changed

# don't use the wrapper as it lacks the shebang so ansible errors out with an exec format error
- name: Install Killing Floor 2 Classic (be patient, 16 GB+)
  command: "dotnet {{ steam_home }}/depotdownloader/DepotDownloader.dll -app 232130 -depot 232131 -manifest 2346945547354693824 -validate -os linux -max-downloads 16 -dir {{ steam_home }}/Steam/KF2Server"
  no_log: True
  become: yes
  become_user: steam
  register: kf2_install
  changed_when: '"Total downloaded: 0 bytes (0 bytes uncompressed) from 1 depots" not in kf2_install.stdout'

- name: Make symlinks for the Workshop and Cache folders
  file:
    src: "{{ item.target }}"
    dest: "{{ item.link }}"
    state: link
    force: yes
    follow: no
    owner: steam
    group: steam
  loop:
  - { target: '{{ steam_home }}/Steam/KF2Server/KFGame/Cache', link: '{{ steam_home }}/Cache' }
  - { target: '{{ steam_home }}/Steam/KF2Server/Binaries/Win64/steamapps/workshop', link: '{{ steam_home }}/Workshop' }

- name: Add killinuxfloor repo
  copy:
    src: killinuxfloor.repo
    dest: /etc/yum.repos.d/killinuxfloor.repo
  register: klf_repo

- name: Update yum cache
  yum:
    update_cache: yes
  when: klf_repo.changed

- name: Install killinuxfloor packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - killinuxfloor-balance
