---
- include_tasks: os.yml
- include_tasks: steam.yml
- include_tasks: kf2.yml
- include_tasks: systemd.yml
- include_tasks: sudo.yml
- include_tasks: firewalld.yml
- include_tasks: config.yml
- include_tasks: autokick.yml
